### Baseline RBO
Here we will compute the baseline Rank-Biased Overlap (RBO) values for a range of depths and persistences. It generates randomized feature importance lists and calculates the RBO between each pair of lists for different depths and persistences. It follows a step-by-step process, including generating random feature importance lists, calculating RBOs, and computing the mean RBO values. The output DataFrame provides insights into the baseline RBO scores, which serve as a reference point for evaluating the similarity of actual feature importance rankings.

In [1]:
from util.commons import calculate_baseline_rbo, _calculate_rbo
from matplotlib import cm

In [2]:
baseline_df = calculate_baseline_rbo(5, 25, 1, 64, 1000)

In [3]:
display(baseline_df.style
        .hide_index()
        .background_gradient(
            subset=['Mean'],
            cmap=cm.get_cmap('Reds')))

In [4]:
display(baseline_df[baseline_df['Mean'] == baseline_df['Mean'].max()])

       p   d      Mean
20  0.96  25  0.250017